### ISSUE TITLE
bug 注意！！！！！！按钮多次抖动导致无法进入 长按回调函数解决方法！！！！！！！！！

### ISSUE THREAD

**Issue by logicDance-mcu** [liu2guang/MultiButton#3]
在multi button .c文件

第174行！！！！

添加 else {
handle->state = 0;
}
即可解决，

不然会导致长按不生效
！！！！

**Comment by logicDance-mcu** [comment]
else if(handle->ticks > SHORT_TICKS){
handle->state = 0;
}

添加成这个

**Comment by mysterywolf** [comment]
你好 请你把这个bug反馈给上游仓库：https://github.com/0x1abin/MultiButton

**Comment by idfulin** [comment]
![image](https://user-images.githubusercontent.com/26590279/115073392-dc654800-9f2a-11eb-9a56-9b8218142169.png)
此处应该还有一个状态切换，对应代码应该修改下面部分
![image](https://user-images.githubusercontent.com/26590279/115073489-fbfc7080-9f2a-11eb-94da-645739db4a1a.png)

下面是我的建议，供参考
    case 3:
        if(handle->button_level != handle->active_level)
        {
            handle->event = (uint8_t)PRESS_UP;
            EVENT_CB(PRESS_UP);

            if(handle->ticks < SHORT_TICKS)
            {
                handle->ticks = 0;
                handle->state = 2;
            }
            else
            {
                handle->state = 0;
            }
        }
        else if (handle->ticks > LONG_TICKS)
        {
            handle->state = 5;
        }
        break;

**Comment by mysterywolf** [comment]
@idfulin 你好 这里还有一个和你差不多的代码，他建议是回到0，你觉得回到哪个比较好呢？
https://github.com/0x1abin/MultiButton/issues/15#issuecomment-699843025

**Comment by Jackistang** [comment]
- 直接切换成状态5会丢失一个 `LONG_PRESS_START` 事件。
- 切换成状态 0 或状态 1 则不会，不过需要再过 `LONG_TICKS` 才能检测到长按事件。这是可以理解的，因为在连击之后突然长按按键，也是需要 `LONG_TICKS` 个时间之后才能触发长按事件。

**Comment by mysterywolf** [comment]
@Jackistang  明白了 handle->ticks > LONG_TICKS 还是 handle->ticks > SHORT_TICKS比较好？

**Comment by mysterywolf** [comment]
@Jackistang https://github.com/liu2guang/MultiButton/pull/5 我提了一个pr， 要不你来提也行。

**Comment by Jackistang** [comment]
如果切换成状态0或者1的话，建议是 `SHORT_TICKS`，因为状态 3 经过 `SHORT_TICKS` 后仍检测到按键按下，这时已有的两个扇出就失效了，可以直接转换状态了。
你可以改改你的 pr，
